### ISSUE TITLE
fail to start service

### ISSUE THREAD

**Issue by putrarifin** [KagurazakaNyaa/palworld-docker#1]
hi nice work..

iam facing this on log compose when start the service.

dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory.

any advice ?

**Comment by limitcool** [comment]
I encountered the same error.

**Comment by KagurazakaNyaa** [comment]
Did you build the image yourself or pull it?
Can I see the `docker-compose.yml` you are using?

**Comment by putrarifin** [comment]
iam using default in your repo. no changes.

**Comment by limitcool** [comment]
I executed docker-compose up  directly.
This is my docker-compose configuration file.
```
version: '3.9'

services:
  dedicated-server:
    image: kagurazakanyaa/palworld:latest
    build:
      context: .
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8211:8211/udp
    environment:
      - GAME_PORT=8211
      - MAX_PLAYERS=32
      - ENABLE_MULTITHREAD=true
      - IS_PUBLIC=false
      - PUBLIC_IP=
      - PUBLIC_PORT=
      - FORCE_UPDATE=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/opt/palworld/Pal/Saved
```
This is my error log
```
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
tid(23) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
/tmp/dumps insufficient permissions - delete and recreate
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
tid(35) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '2394010' state is 0x202 after update job.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
The command '/bin/sh -c /home/steam/steamcmd/steamcmd.sh +force_install_dir "/opt/palworld" +login anonymous +app_update 2394010 validate +quit' returned a non-zero code: 8
ERROR: Service 'dedicated-server' failed to build : Build failed

```
